In [ ]:
# Import libraries
import pandas as pd 
import numpy as np
import sqlite3

In [122]:
conn = sqlite3.connect('Level3_final_project_library.db')

In [123]:
def run (query):
    return pd.read_sql_query(query, conn)

# Task 1

### Get to know the data

In [124]:
run("""
SELECT name 
FROM sqlite_master 
WHERE type='table';
""")

        name
0    members
1      books
2  checkouts

In [125]:
run("""
SELECT * 
FROM members;
""")

,member_id,first_name,last_name,grade,neighborhood,membership_status,join_date
0,1001,Salma,Ibrahim,8.0,Maadi,Active,2023-04-05
1,1002,Fares,Saleh,9.0,Maadi,Active,None
2,1003,Bassel,Hegazy,6.0,Maadi,Active,2025-04-23
3,1004,Fares,Wahba,7.0,Maadi,inactive,2024-10-09
4,1005,Youssef,Halim,9.0,Maadi,Active,2024-05-05
...,...,...,...,...,...,...,...
75,1076,Dina,Wahba,7.0,Shubra,Active,2025-12-13
76,1077,Lina,Rashad,6.0,Shubra,Active,2023-07-08
77,1078,Habiba,Osman,7.0,Shubra,INACTIVE,2023-08-05
78,1079,Rana,Osman,8.0,Shubra,Active,2024-10-27
79,1080,Bassel,Wahba,9.0,Shubra,Active,2023-12-28

In [126]:
run("""
SELECT * 
FROM members;
""")

,member_id,first_name,last_name,grade,neighborhood,membership_status,join_date
0,1001,Salma,Ibrahim,8.0,Maadi,Active,2023-04-05
1,1002,Fares,Saleh,9.0,Maadi,Active,None
2,1003,Bassel,Hegazy,6.0,Maadi,Active,2025-04-23
3,1004,Fares,Wahba,7.0,Maadi,inactive,2024-10-09
4,1005,Youssef,Halim,9.0,Maadi,Active,2024-05-05
...,...,...,...,...,...,...,...
75,1076,Dina,Wahba,7.0,Shubra,Active,2025-12-13
76,1077,Lina,Rashad,6.0,Shubra,Active,2023-07-08
77,1078,Habiba,Osman,7.0,Shubra,INACTIVE,2023-08-05
78,1079,Rana,Osman,8.0,Shubra,Active,2024-10-27
79,1080,Bassel,Wahba,9.0,Shubra,Active,2023-12-28

In [127]:
run("""
SELECT * 
FROM books;
""")

    book_id                    title          author
0       501          The Silver Kite   Amina Darwish
1       502           Desert Compass   Amina Darwish
2       503        The Lantern Maker    Adel Roushdy
3       504      Rooftop Astronomers    Adel Roushdy
4       505      Letters to the Nile       Aya Hafez
5       506      The Paper Boat Club       Aya Hafez
6       507    Fossils and Fireflies     Dalia Serry
7       508    The Quiet Observatory     Dalia Serry
8       509      Marbles and Mirrors     Diaa Sultan
9       510    The Missing Metronome     Diaa Sultan
10      511     Winter in Alexandria    Farida Anwar
11      512   The Cartographer's Cat    Farida Anwar
12      513   Circuits for Beginners    Galal Mounir
13      514    The Robot in Row Nine    Galal Mounir
14      515       Songs of the Oasis      Hoda Bakry
15      516  The Beekeeper's Almanac      Hoda Bakry
16      517  Shadows on the Corniche     Hani Nagati
17      518     The Ninth Lighthouse     Hani Nagati
18      519         Kites Over Cairo  Jasmine Wahdan
19      520     The Copper Telescope  Jasmine Wahdan
20      521    A Garden of Equations      Karim Elwy
21      522      The Puzzle Merchant      Karim Elwy
22      523    Footsteps in the Dust    Laila Shokry
23      524    The Weaver's Daughter    Laila Shokry
24      525     Storms and Sailboats   Mahmoud Rafei
25      526    The Clockwork Orchard   Mahmoud Rafei
26      527     Notes from the Delta  Mona Kholoussy
27      528        The Glass Beehive  Mona Kholoussy
28      529   Riddles of the Red Sea    Sara Tantawy
29      530        The Sandstone Key    Sara Tantawy
30      531    Voices in the Library     Samir Zohdy
31      532        The Last Bookmark     Samir Zohdy

In [128]:
run("""
SELECT * 
FROM checkouts;
""")

     checkout_id  member_id  book_id checkout_date return_date
0           9263       1047      517    2024-10-21  2024-11-07
1           9340       1072      513    2025-08-24  2025-09-01
2           9231       1053      523    2024-02-04  2024-02-16
3           9129       1032      513    2025-06-21  2025-06-29
4           9370       1079      511    2025-11-11  2025-12-03
..           ...        ...      ...           ...         ...
386         9232       1044      513    2025-05-26  2025-06-11
387         9084       1008      511    2024-06-27  2024-07-22
388         9116       1024      519    2025-01-10  2025-02-09
389         9352       1076      501    2025-02-02        None
390         9246       1044      529    2025-06-25  2025-07-04

[391 rows x 5 columns]

In [129]:
#Q1
run("""
SELECT first_name , COUNT(book_id) AS Borrowing_count 
FROM members m 
JOIN checkouts ch 
ON m.member_id = ch.member_id 
GROUP BY first_name;
""")

   first_name  Borrowing_count
0        Adam               24
1       Ahmed               31
2         Ali                1
3        Amir                1
4         Aya               28
5      Bassel               11
6        Dina               16
7       Fares               13
8      Habiba                1
9       Hamza                3
10     Hassan                5
11       Jana                2
12      Karim                1
13      Layla                9
14       Lina               17
15      Malak                9
16      Menna                2
17    Mostafa               25
18       Nada               13
19       Nour               18
20       Rana               17
21       Reem               16
22      Retaj                9
23      Salma                1
24       Sara               16
25       Seif               14
26     Sherif               24
27      Tarek                7
28     Yassin                2
29    Youssef               26
30       Ziad               29

In [130]:
#Q2
run("""SELECT title , author 
FROM books 
WHERE author LIKE 'A%' ;""")

                 title         author
0      The Silver Kite  Amina Darwish
1       Desert Compass  Amina Darwish
2    The Lantern Maker   Adel Roushdy
3  Rooftop Astronomers   Adel Roushdy
4  Letters to the Nile      Aya Hafez
5  The Paper Boat Club      Aya Hafez

In [131]:
#Q3
run("""
SELECT title , COUNT(b.book_id) AS Borrowing_count
FROM books b 
JOIN checkouts ch ON 
b.book_id = ch.book_id 
GROUP BY title 
ORDER BY Borrowing_count DESC 
LIMIT 5;
""")

                    title  Borrowing_count
0         The Silver Kite               57
1   Fossils and Fireflies               55
2  Circuits for Beginners               46
3        Kites Over Cairo               38
4    Storms and Sailboats               25

In [132]:
#Q4
run("""
SELECT first_name , COUNT(book_id) AS Borrowing_count 
FROM members m 
JOIN checkouts ch 
ON m.member_id = ch.member_id 
GROUP BY first_name
ORDER BY Borrowing_count DESC 
LIMIT 10 ;
""")

  first_name  Borrowing_count
0      Ahmed               31
1       Ziad               29
2        Aya               28
3    Youssef               26
4    Mostafa               25
5     Sherif               24
6       Adam               24
7       Nour               18
8       Rana               17
9       Lina               17

In [133]:
#Q5
run("""
SELECT first_name , COUNT(book_id) AS Borrowing_count , neighborhood , checkout_date
FROM members m
JOIN checkouts ch 
ON m.member_id = ch.member_id 
WHERE neighborhood ='Maadi'
GROUP BY first_name
ORDER BY checkout_date DESC 
LIMIT 10 OFFSET 11
""")

  first_name  Borrowing_count neighborhood checkout_date
0      Salma                1        Maadi    2024-10-24
1    Youssef                9        Maadi    2024-04-22
2       Dina                7        Maadi    2024-04-15
3     Habiba                1        Maadi    2024-03-06
4      Fares                2        Maadi    2024-02-16

In [134]:
t1 = run("""
            SELECT * 
            FROM members    
                       """)

t2 = run("""
            SELECT * 
            FROM checkouts    
                       """)
combined_tables = pd.merge(t1, t2 ,on='member_id', how='left' )

In [135]:
combined_tables['Borrowing_count'] = combined_tables.groupby('member_id')['checkout_id'].transform('count')

In [136]:
combined_tables

,member_id,first_name,last_name,grade,neighborhood,membership_status,join_date,checkout_id,book_id,checkout_date,return_date,Borrowing_count
0,1001,Salma,Ibrahim,8.0,Maadi,Active,2023-04-05,9025.0,525.0,2024-10-24,2024-11-07,1
1,1002,Fares,Saleh,9.0,Maadi,Active,None,9013.0,501.0,2024-02-16,2024-02-29,2
2,1002,Fares,Saleh,9.0,Maadi,Active,None,9095.0,507.0,2024-06-25,2024-07-07,2
3,1003,Bassel,Hegazy,6.0,Maadi,Active,2025-04-23,9051.0,513.0,2025-07-22,2025-08-18,9
4,1003,Bassel,Hegazy,6.0,Maadi,Active,2025-04-23,9068.0,501.0,2025-11-14,2025-12-03,9
...,...,...,...,...,...,...,...,...,...,...,...,...
404,1079,Rana,Osman,8.0,Shubra,Active,2024-10-27,9381.0,507.0,2025-05-30,2025-06-18,10
405,1079,Rana,Osman,8.0,Shubra,Active,2024-10-27,9367.0,507.0,2024-03-19,2024-03-28,10
406,1079,Rana,Osman,8.0,Shubra,Active,2024-10-27,9373.0,508.0,2024-03-20,2024-04-19,10
407,1080,Bassel,Wahba,9.0,Shubra,Active,2023-12-28,9350.0,501.0,2025-06-22,2025-07-17,2
408,1080,Bassel,Wahba,9.0,Shubra,Active,2023-12-28,9374.0,505.0,2024-08-05,2024-08-12,2

In [137]:
combined_tables.shape

(409, 12)

In [138]:
catalog = pd.read_json("Book Catalog.json")
combined_tables_catalog = pd.merge(combined_tables , catalog , on='book_id', how='inner')
combined_tables_catalog

,member_id,first_name,last_name,grade,neighborhood,membership_status,join_date,checkout_id,book_id,checkout_date,return_date,Borrowing_count,genre,pages,publication_year,publisher
0,1001,Salma,Ibrahim,8.0,Maadi,Active,2023-04-05,9025.0,525.0,2024-10-24,2024-11-07,1,Adventure,297,2015.0,Oasis Books
1,1002,Fares,Saleh,9.0,Maadi,Active,None,9013.0,501.0,2024-02-16,2024-02-29,2,Adventure,128,2017.0,Nile Press
2,1002,Fares,Saleh,9.0,Maadi,Active,None,9095.0,507.0,2024-06-25,2024-07-07,2,Science,160,2024.0,Nile Press
3,1003,Bassel,Hegazy,6.0,Maadi,Active,2025-04-23,9051.0,513.0,2025-07-22,2025-08-18,9,Science,294,2021.0,Oasis Books
4,1003,Bassel,Hegazy,6.0,Maadi,Active,2025-04-23,9068.0,501.0,2025-11-14,2025-12-03,9,Adventure,128,2017.0,Nile Press
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
386,1079,Rana,Osman,8.0,Shubra,Active,2024-10-27,9381.0,507.0,2025-05-30,2025-06-18,10,Science,160,2024.0,Nile Press
387,1079,Rana,Osman,8.0,Shubra,Active,2024-10-27,9367.0,507.0,2024-03-19,2024-03-28,10,Science,160,2024.0,Nile Press
388,1079,Rana,Osman,8.0,Shubra,Active,2024-10-27,9373.0,508.0,2024-03-20,2024-04-19,10,Science,306,2011.0,Oasis Books
389,1080,Bassel,Wahba,9.0,Shubra,Active,2023-12-28,9350.0,501.0,2025-06-22,2025-07-17,2,Adventure,128,2017.0,Nile Press
390,1080,Bassel,Wahba,9.0,Shubra,Active,2023-12-28,9374.0,505.0,2024-08-05,2024-08-12,2,Historical,216,2024.0,Oasis Books

In [139]:
combined_tables_catalog.shape

(391, 16)

In [140]:
kickoffs = pd.read_html("Reading Kickoff Signups.html")[0]
kickoffs.columns = ["member_id" ,"book_id" , "checkout_date" ]


full_kickoffs =  pd.merge(kickoffs,t1 , on = "member_id" , how = "left")
full_kickoffs =  pd.merge(full_kickoffs,catalog , on = "book_id" , how = "left")
combined_data = pd.concat([combined_tables_catalog , full_kickoffs] , ignore_index= True)

combined_data['Borrowing_count'] = combined_data.groupby('member_id')['checkout_date'].transform('count')

In [141]:
kickoffs

    member_id  book_id checkout_date
0        1026      522    2025-07-11
1        1049      520    2025-07-11
2        1062      525    2025-07-05
3        1065      520    2025-07-07
4        1104      515    2025-07-07
5        1009      503    2025-07-09
6        1063      522    2025-07-07
7        1022      511    2025-07-12
8        1029      523    2025-07-09
9        1201      509    2025-07-10
10       1005      513    2025-07-10
11       1104      526    2025-07-05
12       1058      518    2025-07-08
13       1002      521    2025-07-08
14       1150      530    2025-07-10
15       1041      504    2025-07-05
16       1055      526    2025-07-11
17       1061      513    2025-07-06
18       1012      509    2025-07-11
19       1007      510    2025-07-07
20       1073      530    2025-07-07
21       1003      501    2025-07-08
22       1017      507    2025-07-11
23       1061      504    2025-07-06
24       1201      523    2025-07-08
25       1041      512    2025-07-06

In [142]:
combined_data

,member_id,first_name,last_name,grade,neighborhood,membership_status,join_date,checkout_id,book_id,checkout_date,return_date,Borrowing_count,genre,pages,publication_year,publisher
0,1001,Salma,Ibrahim,8.0,Maadi,Active,2023-04-05,9025.0,525.0,2024-10-24,2024-11-07,1,Adventure,297,2015.0,Oasis Books
1,1002,Fares,Saleh,9.0,Maadi,Active,None,9013.0,501.0,2024-02-16,2024-02-29,3,Adventure,128,2017.0,Nile Press
2,1002,Fares,Saleh,9.0,Maadi,Active,None,9095.0,507.0,2024-06-25,2024-07-07,3,Science,160,2024.0,Nile Press
3,1003,Bassel,Hegazy,6.0,Maadi,Active,2025-04-23,9051.0,513.0,2025-07-22,2025-08-18,10,Science,294,2021.0,Oasis Books
4,1003,Bassel,Hegazy,6.0,Maadi,Active,2025-04-23,9068.0,501.0,2025-11-14,2025-12-03,10,Adventure,128,2017.0,Nile Press
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
412,1003,Bassel,Hegazy,6.0,Maadi,Active,2025-04-23,NaN,501.0,2025-07-08,NaN,10,Adventure,128,2017.0,Nile Press
413,1017,Adam,Badr,9.0,Maadi,Active,2025-07-12,NaN,507.0,2025-07-11,NaN,3,Science,160,2024.0,Nile Press
414,1061,Ziad,Fahmy,9.0,zamalek,Inactive,2023-04-27,NaN,504.0,2025-07-06,NaN,10,Science,319,2009.0,Cairo Young Readers
415,1201,NaN,NaN,NaN,NaN,NaN,NaN,NaN,523.0,2025-07-08,NaN,2,Historical,276,2018.0,Oasis Books
416,1041,Nada,Rashad,7.0,Nasr City,Active,2024-04-02,NaN,512.0,2025-07-06,NaN,4,Adventure,238,2022.0,Delta House

In [143]:
combined_data.to_csv("30801151901074-library-task1_combined_data.csv" , index = False)

# Task 2

In [144]:
data = pd.read_csv("30801151901074-library-task1_combined_data.csv")

In [145]:
data.head()

,member_id,first_name,last_name,grade,neighborhood,membership_status,join_date,checkout_id,book_id,checkout_date,return_date,Borrowing_count,genre,pages,publication_year,publisher
0,1001,Salma,Ibrahim,8.0,Maadi,Active,2023-04-05,9025.0,525.0,2024-10-24,2024-11-07,1,Adventure,297,2015.0,Oasis Books
1,1002,Fares,Saleh,9.0,Maadi,Active,NaN,9013.0,501.0,2024-02-16,2024-02-29,3,Adventure,128,2017.0,Nile Press
2,1002,Fares,Saleh,9.0,Maadi,Active,NaN,9095.0,507.0,2024-06-25,2024-07-07,3,Science,160,2024.0,Nile Press
3,1003,Bassel,Hegazy,6.0,Maadi,Active,2025-04-23,9051.0,513.0,2025-07-22,2025-08-18,10,Science,294,2021.0,Oasis Books
4,1003,Bassel,Hegazy,6.0,Maadi,Active,2025-04-23,9068.0,501.0,2025-11-14,2025-12-03,10,Adventure,128,2017.0,Nile Press

In [161]:
data.tail()

,member_id,first_name,last_name,grade,neighborhood,membership_status,join_date,checkout_id,book_id,checkout_date,return_date,Borrowing_count,genre,pages,publication_year,publisher
412,1003,Bassel,Hegazy,6.0,Maadi,Active,2025-04-23,NaN,501.0,2025-07-08,2025-08-31,10,Adventure,128,2017.0,Nile Press
413,1017,Adam,Badr,9.0,Maadi,Active,2025-07-12,NaN,507.0,2025-07-11,2025-08-31,3,Science,160,2024.0,Nile Press
414,1061,Ziad,Fahmy,9.0,zamalek,Inactive,2023-04-27,NaN,504.0,2025-07-06,2025-08-31,10,Science,319,2009.0,Cairo Young Readers
415,1201,NaN,NaN,NaN,NaN,NaN,NaN,NaN,523.0,2025-07-08,2025-08-31,2,Historical,276,2018.0,Oasis Books
416,1041,Nada,Rashad,7.0,Nasr City,Active,2024-04-02,NaN,512.0,2025-07-06,2025-08-31,4,Adventure,238,2022.0,Delta House

In [146]:
data.shape

(417, 16)

In [147]:
data.describe()

,member_id,grade,checkout_id,book_id,Borrowing_count,pages,publication_year
count,417.000000,376.000000,391.000000,417.000000,417.000000,417.000000,382.000000
mean,1041.004796,7.577128,9192.611253,513.443645,11.968825,202.299760,2017.426702
std,26.356925,1.154427,110.279771,8.976053,6.972231,73.986738,4.567214
min,1001.000000,6.000000,9001.000000,501.000000,1.000000,104.000000,2009.000000
25%,1020.000000,7.000000,9097.500000,507.000000,6.000000,134.000000,2014.000000
50%,1036.000000,8.000000,9193.000000,513.000000,11.000000,160.000000,2017.000000
75%,1061.000000,9.000000,9287.500000,519.000000,18.000000,294.000000,2021.000000
max,1201.000000,9.000000,9383.000000,532.000000,25.000000,338.000000,2024.000000

In [148]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 417 entries, 0 to 416
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   member_id          417 non-null    int64
 1   first_name         412 non-null    object
 2   last_name          412 non-null    object
 3   grade              376 non-null    float64
 4   neighborhood       412 non-null    object
 5   membership_status  412 non-null    object
 6   join_date          406 non-null    object
 7   checkout_id        391 non-null    float64
 8   book_id            417 non-null    float64
 9   checkout_date      417 non-null    object
 10  return_date        326 non-null    object
 11  Borrowing_count    417 non-null    int64
 12  genre              417 non-null    object
 13  pages              417 non-null    int64
 14  publication_year   382 non-null    float64
 15  publisher          417 non-null    object
dtypes: float64(4), int64(3), object(9)
memory usage: 52.3+ KB

In [149]:
print(data.columns.tolist())

['member_id', 'first_name', 'last_name', 'grade', 'neighborhood', 'membership_status', 'join_date', 'checkout_id', 'book_id', 'checkout_date', 'return_date', 'Borrowing_count', 'genre', 'pages', 'publication_year', 'publisher']

In [150]:
data.duplicated().sum()

np.int64(8)

In [ ]:
# Duplicates first cause it could lead to less nulls 
data_cleaned = data.drop_duplicates(keep="first").copy

In [151]:
data.duplicated().sum()

np.int64(8)

In [152]:
data.isna().sum()

member_id             0
first_name            5
last_name             5
grade                41
neighborhood          5
membership_status     5
join_date            11
checkout_id          26
book_id               0
checkout_date         0
return_date          91
Borrowing_count       0
genre                 0
pages                 0
publication_year     35
publisher             0
dtype: int64

In [ ]:
#the kickoffs Nan records 
data.tail(26).isna().sum()

member_id             0
first_name            5
last_name             5
grade                 5
neighborhood          5
membership_status     5
join_date             6
checkout_id          26
book_id               0
checkout_date         0
return_date          26
Borrowing_count       0
genre                 0
pages                 0
publication_year      1
publisher             0
dtype: int64

In [ ]:
# Fill the kickoffs data first 
data["return_date"] = pd.to_datetime(data["return_date"])
kickoffs_return_date = data["return_date"].isna() & data["checkout_id"].isna()
data.loc[kickoffs_return_date , "return_date"] = pd.Timestamp('2025-08-31')

In [162]:
data["join_date"] = pd.to_datetime(data["join_date"])
kickoffs_join_date = data["join_date"].isna() & data["checkout_id"].isna()
data.loc[kickoffs_join_date , "join_date"] = pd.Timestamp('2025-06-01')

In [169]:
latest_id = data["checkout_id"].max()
missing_mask = data["checkout_id"].isna()
missing_ids = missing_mask.sum()
data.loc[missing_mask,"checkout_id"] = (range(int(latest_id) + 1 , int(latest_id) + 1 + missing_ids))

In [170]:
data.tail(26).isna().sum()

member_id            0
first_name           5
last_name            5
grade                5
neighborhood         5
membership_status    5
join_date            0
checkout_id          0
book_id              0
checkout_date        0
return_date          0
Borrowing_count      0
genre                0
pages                0
publication_year     1
publisher            0
dtype: int64

In [171]:
data.isna().sum()

member_id             0
first_name            5
last_name             5
grade                41
neighborhood          5
membership_status     5
join_date             5
checkout_id           0
book_id               0
checkout_date         0
return_date          65
Borrowing_count       0
genre                 0
pages                 0
publication_year     35
publisher             0
dtype: int64

In [172]:
data["grade"].value_counts()

grade
9.0    113
6.0     91
7.0     90
8.0     82
Name: count, dtype: int64