In [1]:
# Import libraries
import pandas as pd 
import sqlite3
import matplotlib.pyplot as plt

In [2]:
conn = sqlite3.connect('Level3_final_project_library.db')

In [3]:
def run (query):
    return pd.read_sql_query(query, conn)

In [4]:
run("""
SELECT name 
FROM sqlite_master 
WHERE type='table';
""")

        name
0    members
1      books
2  checkouts

In [5]:
run("""
SELECT * 
FROM members;
""")

,member_id,first_name,last_name,grade,neighborhood,membership_status,join_date
0,1001,Salma,Ibrahim,8.0,Maadi,Active,2023-04-05
1,1002,Fares,Saleh,9.0,Maadi,Active,None
2,1003,Bassel,Hegazy,6.0,Maadi,Active,2025-04-23
3,1004,Fares,Wahba,7.0,Maadi,inactive,2024-10-09
4,1005,Youssef,Halim,9.0,Maadi,Active,2024-05-05
...,...,...,...,...,...,...,...
75,1076,Dina,Wahba,7.0,Shubra,Active,2025-12-13
76,1077,Lina,Rashad,6.0,Shubra,Active,2023-07-08
77,1078,Habiba,Osman,7.0,Shubra,INACTIVE,2023-08-05
78,1079,Rana,Osman,8.0,Shubra,Active,2024-10-27
79,1080,Bassel,Wahba,9.0,Shubra,Active,2023-12-28

In [ ]:
run("""
SELECT * 
FROM books;
""")

    book_id                    title          author
0       501          The Silver Kite   Amina Darwish
1       502           Desert Compass   Amina Darwish
2       503        The Lantern Maker    Adel Roushdy
3       504      Rooftop Astronomers    Adel Roushdy
4       505      Letters to the Nile       Aya Hafez
5       506      The Paper Boat Club       Aya Hafez
6       507    Fossils and Fireflies     Dalia Serry
7       508    The Quiet Observatory     Dalia Serry
8       509      Marbles and Mirrors     Diaa Sultan
9       510    The Missing Metronome     Diaa Sultan
10      511     Winter in Alexandria    Farida Anwar
11      512   The Cartographer's Cat    Farida Anwar
12      513   Circuits for Beginners    Galal Mounir
13      514    The Robot in Row Nine    Galal Mounir
14      515       Songs of the Oasis      Hoda Bakry
15      516  The Beekeeper's Almanac      Hoda Bakry
16      517  Shadows on the Corniche     Hani Nagati
17      518     The Ninth Lighthouse     Hani Nagati
18      519         Kites Over Cairo  Jasmine Wahdan
19      520     The Copper Telescope  Jasmine Wahdan
20      521    A Garden of Equations      Karim Elwy
21      522      The Puzzle Merchant      Karim Elwy
22      523    Footsteps in the Dust    Laila Shokry
23      524    The Weaver's Daughter    Laila Shokry
24      525     Storms and Sailboats   Mahmoud Rafei
25      526    The Clockwork Orchard   Mahmoud Rafei
26      527     Notes from the Delta  Mona Kholoussy
27      528        The Glass Beehive  Mona Kholoussy
28      529   Riddles of the Red Sea    Sara Tantawy
29      530        The Sandstone Key    Sara Tantawy
30      531    Voices in the Library     Samir Zohdy
31      532        The Last Bookmark     Samir Zohdy

In [6]:
run("""
SELECT * 
FROM checkouts;
""")

     checkout_id  member_id  book_id checkout_date return_date
0           9263       1047      517    2024-10-21  2024-11-07
1           9340       1072      513    2025-08-24  2025-09-01
2           9231       1053      523    2024-02-04  2024-02-16
3           9129       1032      513    2025-06-21  2025-06-29
4           9370       1079      511    2025-11-11  2025-12-03
..           ...        ...      ...           ...         ...
386         9232       1044      513    2025-05-26  2025-06-11
387         9084       1008      511    2024-06-27  2024-07-22
388         9116       1024      519    2025-01-10  2025-02-09
389         9352       1076      501    2025-02-02        None
390         9246       1044      529    2025-06-25  2025-07-04

[391 rows x 5 columns]

In [7]:
run("""
SELECT first_name , COUNT(book_id) AS Borrowing_count 
FROM members m 
JOIN checkouts ch 
ON m.member_id = ch.member_id 
GROUP BY first_name;
""")

   first_name  Borrowing_count
0        Adam               24
1       Ahmed               31
2         Ali                1
3        Amir                1
4         Aya               28
5      Bassel               11
6        Dina               16
7       Fares               13
8      Habiba                1
9       Hamza                3
10     Hassan                5
11       Jana                2
12      Karim                1
13      Layla                9
14       Lina               17
15      Malak                9
16      Menna                2
17    Mostafa               25
18       Nada               13
19       Nour               18
20       Rana               17
21       Reem               16
22      Retaj                9
23      Salma                1
24       Sara               16
25       Seif               14
26     Sherif               24
27      Tarek                7
28     Yassin                2
29    Youssef               26
30       Ziad               29

In [8]:
run("""SELECT title , author 
FROM books 
WHERE author LIKE 'A%' ;""")

                 title         author
0      The Silver Kite  Amina Darwish
1       Desert Compass  Amina Darwish
2    The Lantern Maker   Adel Roushdy
3  Rooftop Astronomers   Adel Roushdy
4  Letters to the Nile      Aya Hafez
5  The Paper Boat Club      Aya Hafez

In [9]:
run("""
SELECT title , COUNT(b.book_id) AS Borrowing_count
FROM books b 
JOIN checkouts ch ON 
b.book_id = ch.book_id 
GROUP BY title 
ORDER BY Borrowing_count DESC 
LIMIT 5;
""")

                    title  Borrowing_count
0         The Silver Kite               57
1   Fossils and Fireflies               55
2  Circuits for Beginners               46
3        Kites Over Cairo               38
4    Storms and Sailboats               25

In [10]:
run("""
SELECT first_name , COUNT(book_id) AS Borrowing_count 
FROM members m 
JOIN checkouts ch 
ON m.member_id = ch.member_id 
GROUP BY first_name
ORDER BY Borrowing_count DESC 
LIMIT 10 ;
""")

  first_name  Borrowing_count
0      Ahmed               31
1       Ziad               29
2        Aya               28
3    Youssef               26
4    Mostafa               25
5     Sherif               24
6       Adam               24
7       Nour               18
8       Rana               17
9       Lina               17

In [11]:
run("""
SELECT first_name , COUNT(book_id) AS Borrowing_count , neighborhood , checkout_date
FROM members m
JOIN checkouts ch 
ON m.member_id = ch.member_id 
WHERE neighborhood ='Maadi'
GROUP BY first_name
ORDER BY checkout_date DESC 
LIMIT 10 OFFSET 11
""")

  first_name  Borrowing_count neighborhood checkout_date
0      Salma                1        Maadi    2024-10-24
1    Youssef                9        Maadi    2024-04-22
2       Dina                7        Maadi    2024-04-15
3     Habiba                1        Maadi    2024-03-06
4      Fares                2        Maadi    2024-02-16